### ISSUE TITLE
USB Interface - G29

### ISSUE THREAD

**Issue by A2H1M** [Speedgoat-Application-Engineering-Team/Real-Time-Driver-in-the-Loop#10]
In our project (5th semester - mechatronics) we would like to build a driving simulator which is linked to a Simulink model.

Important for us is the implementation of the Logitech steering wheel G29 via USB.

We couldnt find any solutions for using the G29 directly with the host computer in your code.

Perhaps we have overlooked something,

with kind regards from Germany

A2H1M

**Comment by tstraessle** [comment]
Hi. Thanks for your question. We are using the "Joystick Input" block from the "Simulink 3D Animation" toolbox, to read in the signals from the G29 steering wheel to the host computer.
In our reference application, we forward these signals to the real-time target machine for simulation of the vehicle dynamics, but this is not required if you want to perform desktop simulation only.
I hope this helps, sorry for the late response.
