### ISSUE TITLE
Replace UDP send blocks on host model

### ISSUE THREAD

**Issue by pablorcum** [Speedgoat-Application-Engineering-Team/Real-Time-Driver-in-the-Loop#2]
The UDP send blocks in the DriverInLoopGamingEngine model comes from the SLRT library. After MALTAB R2020b, these blocks are no longer functional on desktop and should be replaced with the corresponding blocks from either the Instrument Control Toolbox or the DSP System Toolbox.

**Comment by tstraessle** [comment]
With the latest updates to MATLAB R2020b, the blocks are again functional on the host as well.
