### ISSUE TITLE
Set referenced models to Normal and remove bin files

### ISSUE THREAD

**Issue by pablorcum** [Speedgoat-Application-Engineering-Team/Real-Time-Driver-in-the-Loop#7]
Please set simulation mode to Normal for referenced models instead of accelerator. That allows removing the mex files. As the model will run in real-time on the Speedgoat, generating code, it does not improve any performance having them to Accelerator but in the contrary, makes the diagram's update slower.

**Comment by tstraessle** [comment]
Thanks. Fixed in v3.0.2
